name: Docker Series Builds

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}   
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: docker build alpine
      run: |
        docker build ./alpine/Dockerfile
    - name: docker build NGINX
      run: |
        docker build ./NGINX/Dockerfile
    - name: docker push
      run: |
        docker push ./alpine/Dockerfile
        docker push ./NGINX/Dockerfile
